// Generated by CoffeeScript 1.6.3
define(function() {
  var setup;
  setup = function(options) {
    this.paths = {
      'knockout.validation': "" + options.ref + "lib/knockout.validation",
      'knockout.viewmodel': "" + options.ref + "lib/knockout.viewmodel",
      clientEnrollModel: "absolute/common/models/clientEnrollModel",
      transitions: "" + options.ref + "lib/durandal/transitions",
      lib: "" + options.ref + "lib",
      specs: "" + options.ref + "specs",
      app: "" + options.ref + "app",
      "common": "/absolute/common",
      "clientEnrollModel": "/absolute/common/models/us/client",
      "enrollModel": "/absolute/common/models/us/enroll"
    };
    this.bootstrap = ["knockout.validation", "knockout.viewmodel"];
    this.mock = function() {
      define('pathPlugins', function() {});
      define('pathConfig', function() {});
      define('text!index.html', function() {
        return '';
      });
    };
  };
  return setup;
});
