// Generated by CoffeeScript 1.6.3
define(function() {
  ko.bindingHandlers.closeMenu = {
    init: function(element) {
      var el;
      el = $(element);
      if (el.hammer == null) {
        return;
      }
      el.hammer().on("swipeleft dragleft", function(event) {
        event.gesture.preventDefault();
        event.gesture.stopPropagation();
        event.gesture.stopDetect();
        document.location.hash = "#";
      });
    }
  };
});
