// Generated by CoffeeScript 1.6.3
define(function() {
  ko.bindingHandlers.jscolor = {
    init: function(element) {
      require(['lib/jscolor'], function() {
        jscolor.init();
      });
    }
  };
});
