// Generated by CoffeeScript 1.6.3
define(function() {
  ko.bindingHandlers.localScroll = {
    init: function(element, valueAccessor) {
      var el, options;
      el = $(element);
      options = valueAccessor();
      el.localScroll({
        target: options.target,
        lazy: true,
        hash: false
      });
    }
  };
});
