// Generated by CoffeeScript 1.6.3
define(function() {
  var closeMenu, openMenu;
  openMenu = function() {
    var menu, menuClose, menuOpen;
    menu = document.getElementById('main-nav');
    menuOpen = document.getElementById('open-menu');
    menuClose = document.getElementById('close-menu');
    menu.style.width = '320px';
    menuClose.style.display = 'block';
    menuOpen.style.display = 'none';
  };
  closeMenu = function() {
    var menu, menuClose, menuOpen;
    menu = document.getElementById('main-nav');
    menuOpen = document.getElementById('open-menu');
    menuClose = document.getElementById('close-menu');
    menu.style.width = '0px';
    menuClose.style.display = 'none';
    menuOpen.style.display = 'block';
  };
  ko.bindingHandlers.closeMenuOnSwipe = {
    init: function(element) {
      var el;
      el = $(element);
      if (el.hammer == null) {
        return;
      }
      el.hammer().on("swipeleft dragleft", function(event) {
        event.gesture.preventDefault();
        event.gesture.stopPropagation();
        event.gesture.stopDetect();
        closeMenu();
      });
    }
  };
  ko.bindingHandlers.closeMenuOnTap = {
    init: function(element) {
      var el;
      el = $(element);
      if (el.hammer == null) {
        return;
      }
      el.hammer().on("tap", function(event) {
        event.gesture.preventDefault();
        event.gesture.stopPropagation();
        event.gesture.stopDetect();
        closeMenu();
      });
    }
  };
  ko.bindingHandlers.openMenuOnSwipe = {
    init: function(element) {
      var el;
      el = $(element);
      if (el.hammer == null) {
        return;
      }
      el.hammer().on("swiperight", function(event) {
        event.gesture.preventDefault();
        event.gesture.stopPropagation();
        event.gesture.stopDetect();
        openMenu();
      });
    }
  };
  ko.bindingHandlers.openMenuOnTap = {
    init: function(element) {
      var el;
      el = $(element);
      if (el.hammer == null) {
        return;
      }
      el.hammer().on("tap", function(event) {
        event.gesture.preventDefault();
        event.gesture.stopPropagation();
        event.gesture.stopDetect();
        openMenu();
      });
    }
  };
});
