// Generated by CoffeeScript 1.6.3
define(function() {
  ko.bindingHandlers.openMenu = {
    init: function(element) {
      var el;
      el = $(element);
      if (el.hammer == null) {
        return;
      }
      el.hammer().on("swiperight", function(event) {
        event.gesture.preventDefault();
        event.gesture.stopPropagation();
        event.gesture.stopDetect();
        document.location.hash = "#main-nav";
      });
    }
  };
});
