// Generated by CoffeeScript 1.6.3
define(['lib/typeahead.bundle.min'], function() {
  ko.bindingHandlers.typeahead = {
    init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
      debugger;
      var el, options;
      el = $(element);
      return options = valueAccessor();
    }
  };
});
