// Generated by CoffeeScript 1.6.3
define(['lib/typeahead.bundle.min'], function() {
  var setupTypeAhead;
  ko.bindingHandlers.typeahead = {
    init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
      var options;
      options = valueAccessor();
      setupTypeAhead(options.list, element.id);
    }
  };
  setupTypeAhead = function(list, id) {
    var bloodHoundOptions, modules;
    bloodHoundOptions = void 0;
    modules = void 0;
    bloodHoundOptions = {
      datumTokenizer: function(d) {
        return Bloodhound.tokenizers.whitespace(d.tokens.join("/ "));
      },
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      limit: 10,
      local: $.map(list, function(moduleName) {
        return {
          value: moduleName,
          tokens: moduleName.split("/")
        };
      })
    };
    modules = new Bloodhound(bloodHoundOptions);
    modules.initialize();
    $("#" + id + " .typeahead").typeahead({
      hint: true,
      highlight: true,
      minLength: 1
    }, {
      name: "modules",
      displayKey: "value",
      source: modules.ttAdapter()
    }).on("typeahead:selected", function($e, datum) {
      var suiteLink, suiteLinkId;
      suiteLink = void 0;
      suiteLinkId = void 0;
      suiteLinkId = "" + datum["value"];
      suiteLink = document.getElementById(suiteLinkId);
      if (suiteLink.children) {
        suiteLink.children[0].click();
      }
    });
  };
});
