// Generated by CoffeeScript 1.6.3
var config;

config = {};

config.path = "./lib/itchcork/";

config.jsUnderTestPath = config.path;

config.jsUnderTestInclude = ['**', '!specs/**'];

config.specsPath = config.jsUnderTestPath + "specs/";

config.framework = "mocha";

module.exports = config;
