// Generated by CoffeeScript 1.6.3
define(function() {
  var setup;
  setup = function(options) {
    this.paths = {
      transitions: "" + options.ref + "lib/durandal/transitions",
      lib: "" + options.ref + "lib",
      specs: "" + options.ref + "specs",
      app: "" + options.ref + "app"
    };
    this.ext = ".coffee";
  };
  return setup;
});
