// Generated by CoffeeScript 1.6.3
define(function(require) {
  var CoverageViewModel, ViewModel;
  ViewModel = require('app/viewModels/viewModel');
  CoverageViewModel = function() {};
  CoverageViewModel.inherits(ViewModel);
  CoverageViewModel.prototype.c = 1;
  CoverageViewModel.prototype.activate = function() {
    ItchCork.viewModel.processed = false;
    this.base.activate(true);
  };
  return new CoverageViewModel();
});
