// Generated by CoffeeScript 1.6.3
define(function(require) {
  var CodeViewModel, ViewModel;
  ViewModel = require('app/viewModels/viewModel');
  CodeViewModel = function() {};
  CodeViewModel.inherits(ViewModel);
  CodeViewModel.prototype.a = 1;
  CodeViewModel.prototype.activate = function() {
    this.base.activate();
  };
  return new CodeViewModel();
});
