// Generated by CoffeeScript 1.6.3
define(function(require) {
  var SpecViewModel, ViewModel;
  ViewModel = require('app/viewModels/viewModel');
  SpecViewModel = function() {};
  SpecViewModel.inherits(ViewModel);
  SpecViewModel.prototype.b = 1;
  SpecViewModel.prototype.activate = function() {
    this.base.activate(false);
  };
  return new SpecViewModel();
});
