// Generated by CoffeeScript 1.6.3
define(['lib/testRunner/runner', 'app/paths'], function(runner, pathSetup) {
  var viewModel;
  viewModel = function() {
    this.m = ItchCork.viewModel;
  };
  viewModel.prototype.activate = function(withCoverage) {
    var pathConfig, ref;
    ref = '../';
    if (withCoverage) {
      ref = '../../';
    }
    pathConfig = new pathSetup({
      ref: ref
    });
    if (!ItchCork.viewModel.processed) {
      runner({
        pathConfig: pathConfig,
        withCoverage: withCoverage
      });
    }
  };
  return viewModel;
});
