// Generated by CoffeeScript 1.6.3
define(['lib/testRunner/runner', 'app/paths'], function(runner, pathSetup) {
  var viewModel;
  viewModel = function() {
    debugger;
    this.m = ItchCork.viewModel;
  };
  viewModel.prototype.activate = function(withCoverage) {
    var pathConfig, ref;
    ref = '../';
    if (withCoverage) {
      ref = '../../';
    }
    pathConfig = new pathSetup({
      ref: ref
    });
    debugger;
    runner({
      pathConfig: pathConfig,
      withCoverage: withCoverage
    });
  };
  return viewModel;
});
