define(['lib/ace/ext-settings_menu',
        "lib/ace/ext-static_highlight",
        "lib/ace/mode-coffee",
        "lib/ace/mode-javascript",
        'lib/ace/token_tooltip',
        'lib/ace/ext-language_tools',
        'lib/ace/ext-themelist',
        'lib/ace/ext-searchbox',
        'lib/ace/ext-keybinding_menu',
        'lib/ace/ext-beautify',
        'lib/ace/theme-cobalt',
        'lib/ace/theme-github',
        'lib/ace/theme-kuroir',
        'lib/ace/theme-twilight',
        'lib/js2coffee/js2coffee',
        'lib/js2coffee/coffee-script'], function () {

    var js2coffeeEditor = function () {
        var js2coffeeOptions = {};
        var editorCoffee = undefined;
        var editorJS = undefined;
        var editorJS_Session = undefined;
        var editorCoffee_Session = undefined;
        var editMode = undefined;
        this.selectedCodeTheme = new ko.observable("terminal");
        this.model = undefined;

        var compileToJavaScript = function () {
            try {

                var input = editorCoffee.getSession().getDocument().getValue();
                var jsOutput = CoffeeScript.compile(input, {bare: true});

                editorJS_Session.getDocument().setValue(jsOutput);

                if (document.querySelector(".infobox-content")) {
                    document.querySelector(".infobox-content").innerText = "";
                }
                if (document.querySelector("#infobox"))
                    document.querySelector("#infobox").style.display = "none";

                editorJS_Session.setScrollTop(0);
                editorJS_Session.setScrollLeft(0);

            } catch (err) {
                console.log(err.message);
                console.log(err.stack);
                if (document.querySelector(".infobox-content"))
                    document.querySelector(".infobox-content").innerText = err.message;

                if (document.querySelector("#infobox"))
                    document.querySelector("#infobox").style.display = "block";
            }
        }

        var compileToCoffee = function () {
            try {

                var input = editorJS.getSession().getDocument().getValue();
                var coffeeOutput = Js2coffee.build(input, js2coffeeOptions);
                coffeeOutput = coffeeOutput.replace(/(# Generated by CoffeeScript [0-9].[0-9].[0-9]\n)(.*?)/g, '$2')
                editorCoffee_Session.getDocument().setValue(coffeeOutput);

                if (document.querySelector(".infobox-content")) {
                    document.querySelector(".infobox-content").innerText = "";
                }
                if (document.querySelector("#infobox"))
                    document.querySelector("#infobox").style.display = "none";

                editorCoffee_Session.setScrollTop(0);
                editorCoffee_Session.setScrollLeft(0);
            } catch (err) {
                console.log(err.message);
                console.log(err.stack);
                document.querySelector(".infobox-content").innerText = err.message;
                document.querySelector("#infobox").style.display = "block";
            }
        };

        this.saveCoffee = (function (_this) {
            return function () {
                var moduleInfo = {
                    name: _this.model.moduleName(),
                    ext: ".coffee",
                    code: editorCoffee.getSession().getDocument().getValue()
                };
                _this.model.coffeeSourceStr(editorCoffee.getSession().getDocument().getValue())
                $.post("/saveModule", {
                    moduleInfo: JSON.stringify(moduleInfo)
                }, function () {

                });
            };

        })(this);


        this.update = (function (_this) {
            return function (updatedModel) {
                _this.model = updatedModel;
                if (updatedModel.coffeeSourceStr().length > 0) {
                    editorCoffee_Session.getDocument().setValue(updatedModel.coffeeSourceStr());
                } else {
                    editorJS_Session.getDocument().setValue(updatedModel.jsSourceStr());
                    //  compileToCoffee();
                }
            };
        })(this);

        this.init = (function (_this) {
            return function (model) {

                js2coffeeOptions.show_src_lineno = false;

                var TokenTooltip = ace.require("lib/ace/token_tooltip").TokenTooltip;
                ace.require("lib/ace/ext-language_tools");

                editorCoffee = ace.edit("editorCoffee");
                editorCoffee.setOptions({
                    enableBasicAutocompletion: true
                });

                editorCoffee_Session = editorCoffee.getSession();
                editorCoffee_Session.setTabSize(2);
                editorCoffee_Session.setMode("ace/mode/coffee");
                editorCoffee.setFontSize(12);
                ace.require('ace/ext/settings_menu').init(editorCoffee);



                editorCoffee.commands.addCommand({
                    name: 'toggle module list',
                    bindKey: "alt+1",
                    exec: function (editor) {
                        if ($("#suite-list:visible").length > 0) {
                            $("#suite-list").hide();
                            $("#suite-selected").removeClass("col-md-9").addClass("col-md-12");
                        }
                        else {
                            $("#suite-list:hidden").show();
                            $("#suite-selected").removeClass("col-md-12").addClass("col-md-9");
                        }

                    },
                    readOnly: false
                });

                editorCoffee.commands.addCommand({
                    name: 'save module',
                    bindKey: "alt+s",
                    exec: function (editor) {
                        _this.saveCoffee();
                    },
                    readOnly: false
                });

                editorCoffee.commands.addCommands([{
                		name: "showSettingsMenu",
                		bindKey: {win: "alt-q", mac: "Command-q"},
                		exec: function(editor) {
                			editor.showSettingsMenu();
                		},
                		readOnly: true
                	}]);


                editorJS = ace.edit("editorJS");
                editorJS_Session = editorJS.getSession()
                editorJS_Session.setTabSize(2);
                editorJS_Session.setMode("ace/mode/javascript");
                editorJS.setFontSize(12);

//                editorJS_Session.on('changeScrollTop', function () {
//                    editorCoffee_Session.setScrollTop(editorJS_Session.getScrollTop())
//                });
//
//                editorCoffee_Session.on('changeScrollTop', function () {
//                    editorJS_Session.setScrollTop(editorCoffee_Session.getScrollTop())
//                });


                var toggleMode = function () {
                    if (editMode === editorCoffee) {
                        editMode = editorJS;
                    } else if (editMode === editorJS) {
                        editMode = editorCoffee;
                    }
                    schedule();
                }

                editorCoffee.on('change', function (event, editor) {
                    var focused = document.activeElement.parentElement;
                    if (focused === editorCoffee.container) {
                        editMode = editorCoffee;
                        compileToJavaScript();
                    }
                });

                editorJS.on('change', function (event, editor) {
                    var focused = document.activeElement.parentElement;
                    if (focused === editorJS.container) {
                        editMode = editorJS;
                        compileToCoffee()
                    }
                });


                var job = null;
                var schedule = function () {
                    if (job != null) {
                        clearTimeout(job);
                    }
                    return job = setTimeout(doCompile, 200);
                };

                var doCompile = function () {
                    if (editMode === editorCoffee) {
                        compileToJavaScript();
                    } else {
                        compileToCoffee();
                    }
                }

                var enableOptions = function (editors) {
                    for (var i = 0; i < editors.length; i++) {
                        var editor = editors[i];
                        editor.setTheme("ace/theme/terminal");

                        editor.tokenTooltip = new TokenTooltip(editor);
                        editor.setShowInvisibles(false);
                        editor.renderer.setShowGutter(true);
                        editor.renderer.setShowPrintMargin(false);
                    }
                };

                var disableToolTips = function () {
                    tooltip1 = editorCoffee.tokenTooltip;
                    tooltip2 = editorJS.tokenTooltip;
                    tooltip1.destroy();
                    tooltip2.destroy();
                }

                var enableToolTips = function () {
                    editorCoffee.tokenTooltip = new TokenTooltip(editorCoffee);
                    editorJS.tokenTooltip = new TokenTooltip(editorJS);
                }

                enableOptions([editorCoffee, editorJS]);

                _this.model = model;
                if (model && model.coffeeSourceStr() && model.coffeeSourceStr().length > 0) {
                    editorCoffee.getSession().getDocument().setValue(model.coffeeSourceStr().trim());
                    compileToJavaScript();
                } else {
                    editorJS.getSession().getDocument().setValue(model.jsSourceStr().trim());
                    compileToCoffee();
                }
            };

        })(this);
    };
    return js2coffeeEditor;
})
;
