// Generated by CoffeeScript 1.6.3
define(['itchcork', 'lib/testRunner/runner', 'app/paths'], function(itchcork, runner, pathSetup) {
  var viewModel;
  viewModel = itchcork.suiteView;
  viewModel.activate = function() {
    var pathConfig;
    pathConfig = new pathSetup({
      ref: '../'
    });
    runner({
      pathConfig: pathConfig,
      withCoverage: false
    });
  };
  return viewModel;
});
