// Generated by CoffeeScript 1.6.3
define(function(require) {
  var processSrc, processSrcModule;
  processSrcModule = function(moduleName) {
    var ex, moduleInfo, _error;
    ex = void 0;
    try {
      moduleInfo = {
        name: moduleName,
        type: 'code',
        ext: '.js'
      };
      $.get("/absolute", moduleInfo).done(function(data) {
        return new ItchCork.Suite(moduleName, data);
      });
    } catch (_error) {
      _error = _error;
      ex = _error;
      new ItchCork.Suite(moduleName, null);
      console.log(ex);
    }
  };
  processSrc = function(sourceList, done) {
    var i;
    $("input").on("keydown", function(evt) {
      var $this, size;
      $this = $(this);
      size = parseInt($this.attr("size"));
      if (evt.which === 8) {
        return $this.attr("size", size - 1);
      } else {
        return $this.attr("size", size + 1);
      }
    });
    ItchCork.viewModel.code([]);
    i = 0;
    while (i < sourceList.length) {
      processSrcModule(ItchCork.options.sourceList[i]);
      if (i === ItchCork.options.sourceList.length) {
        if (done) {
          done();
        }
      }
      i++;
    }
  };
  return processSrc;
});
