// Generated by CoffeeScript 1.6.3
define(function(require) {
  var processSrc, processSrcModule;
  processSrcModule = function(moduleName, callback) {
    var ex, _error;
    ex = void 0;
    try {
      if (requirejs.defined(ItchCork.options.sourceList[i])) {
        requirejs.undef(ItchCork.options.sourceList[i]);
      }
      require([moduleName], function(module) {
        new ItchCork.Suite(moduleName, module);
        callback();
      });
    } catch (_error) {
      _error = _error;
      ex = _error;
      new ItchCork.Suite(moduleName, null);
      console.log(ex);
    }
  };
  processSrc = function(sourceList, done) {
    var i;
    $("input").on("keydown", function(evt) {
      var $this, size;
      $this = $(this);
      size = parseInt($this.attr("size"));
      if (evt.which === 8) {
        return $this.attr("size", size - 1);
      } else {
        return $this.attr("size", size + 1);
      }
    });
    ItchCork.viewModel.code([]);
    i = 0;
    while (i < sourceList.length) {
      processSrcModule(ItchCork.options.sourceList[i]);
      require([ItchCork.options.sourceList[i]], function(module) {
        if (i === ItchCork.options.sourceList.length) {
          if (done) {
            done();
          }
        }
      });
      i++;
    }
  };
  return processSrc;
});
