// Generated by CoffeeScript 1.6.3
define(function(require) {
  var runner;
  runner = function(options) {
    var postCoverage, postResults;
    if (!options.withCoverage) {
      requirejs.config({
        baseUrl: "_src",
        paths: options.pathConfig.paths
      });
    } else {
      requirejs.config({
        baseUrl: "_instrumented/_src",
        paths: options.pathConfig.paths
      });
    }
    postResults = function(stats, callback) {
      $.post("/stats", {
        stats: JSON.stringify(stats)
      }, function() {
        if (callback) {
          callback();
        }
      });
    };
    postCoverage = function() {
      debugger;
      var coverage;
      if (window.__coverage__) {
        coverage = JSON.stringify(window.__coverage__.valueOf());
        $.post("/coverage", {
          coverage: coverage
        });
      }
    };
    require(["itchcork", 'lib/js2coffee/js2coffeeEditor', 'lib/typeahead.bundle.min'], function(ItchCork, Js2coffeeEditor) {
      window.editor = new Js2coffeeEditor();
      require(options.pathConfig.bootstrap, function() {
        var mochaDone, mochaRunner;
        if (ItchCork.options.framework === "itchcork") {
          ItchCork.suiteView.unitTestFrameworkManager.set("itchcork");
          ItchCork.on.end = function() {
            postCoverage();
            postResults(ItchCork.stats);
          };
          ItchCork.run();
        } else if (ItchCork.options.framework === "mocha") {
          ItchCork.suiteView.unitTestFrameworkManager.set("mocha");
          mochaRunner = require('lib/testRunner/mochaRunner');
          mochaDone = function(stats) {
            var i, suite;
            postResults(stats);
            postCoverage();
            i = void 0;
            suite = void 0;
            $.get("/sourceList", function(sourceList) {
              var bloodHoundOptions, modules, processSrc;
              bloodHoundOptions = {
                datumTokenizer: function(d) {
                  return Bloodhound.tokenizers.whitespace(d.tokens.join("/ "));
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                limit: 10,
                local: $.map(sourceList, function(moduleName) {
                  return {
                    value: moduleName,
                    tokens: moduleName.split("/")
                  };
                })
              };
              modules = new Bloodhound(bloodHoundOptions);
              modules.initialize();
              $("#bloodhound .typeahead").typeahead({
                hint: true,
                highlight: true,
                minLength: 1
              }, {
                name: "modules",
                displayKey: "value",
                source: modules.ttAdapter()
              }).on('typeahead:selected', function($e, datum) {
                var suiteLink, suiteLinkId;
                suiteLinkId = "" + datum['value'];
                suiteLink = document.getElementById(suiteLinkId);
                if (suiteLink.children) {
                  suiteLink.children[0].click();
                }
              });
              processSrc = function(moduleName, require) {
                var ex;
                try {
                  require([moduleName], function(module) {
                    if (!window.__coverage__) {
                      suite = new ItchCork.Suite(moduleName, module);
                    }
                  });
                } catch (_error) {
                  ex = _error;
                  console.log(ex);
                }
              };
              i = 0;
              while (i < sourceList.length) {
                processSrc(sourceList[i], require);
                i++;
              }
            });
          };
          mochaRunner(ItchCork.options.specs, require, ItchCork, mochaDone);
        }
      });
    });
  };
  return runner;
});
