define ["./customBindings/closeMenu"
        "./customBindings/drag"
        "./customBindings/dragDown"
        "./customBindings/dragEnd"
        "./customBindings/dragLeft"
        "./customBindings/dragRight"
        "./customBindings/hold"
        "./customBindings/jscolor"
        "./customBindings/localScroll"
        "./customBindings/openMenu"
        "./customBindings/swipeLeft"
        "./customBindings/swipeRight"
        "./customBindings/tap"]
