// Generated by CoffeeScript 1.6.3
define(function(require) {
  var clearValues, composition, endValues, fadeOutDuration, slightFade, system;
  system = require("durandal/system");
  composition = require("durandal/composition");
  fadeOutDuration = 100;
  endValues = {
    opacity: 1
  };
  clearValues = {
    opacity: '',
    display: ''
  };
  slightFade = function(context) {
    return system.defer(function(dfd) {
      var duration, endTransition, scrollIfNeeded, startTransition;
      endTransition = function() {
        return dfd.resolve();
      };
      scrollIfNeeded = function() {
        if (!context.keepScrollPosition) {
          return $(document).scrollTop(0);
        }
      };
      if (!context.child) {
        return $(context.activeView).fadeOut(fadeOutDuration, endTransition);
      } else {
        duration = context.duration || 500;
        startTransition = function() {
          var $child, startValues;
          scrollIfNeeded();
          context.triggerAttach();
          startValues = {
            opacity: 0,
            display: 'block'
          };
          $child = $(context.child);
          $child.css(startValues);
          return $child.animate(endValues, {
            duration: duration,
            easing: 'swing',
            always: function() {
              $child.css(clearValues);
              return endTransition();
            }
          });
        };
        if (context.activeView) {
          return $(context.activeView).fadeOut({
            duration: fadeOutDuration,
            always: startTransition
          });
        } else {
          return startTransition();
        }
      }
    }).promise();
  };
  return slightFade;
});
