// Generated by CoffeeScript 1.6.3
define(function() {
  var setup;
  setup = function(options) {
    this.paths = {
      'knockout.validation': "" + options.ref + "lib/knockout.validation",
      'knockout.viewmodel': "" + options.ref + "lib/knockout.viewmodel",
      enrollModel: "" + options.ref + "/_src/common/models/enrollModel",
      transitions: "" + options.ref + "lib/durandal/transitions",
      lib: "" + options.ref + "lib",
      specs: "" + options.ref + "specs",
      'app/views': "" + options.ref + "app/views"
    };
    this.bootstrap = ['lib/angular/lib'];
    this.testFrameworkDependencies = ['lib/angular/angular-mocks', 'lib/angular/angular-scenario'];
  };
  return setup;
});
