define(['./ToSource', 'lib/when', 'require',"lib/ace/ext/static_highlight", "lib/ace/lib/dom","lib/ace/theme/solarized_dark","lib/ace/theme/pastel_on_dark", "lib/ace/mode/coffee", "lib/ace/mode/javascript"]
    , function (ToSource, when, require, Js2coffeeEditor) {

        function CodeProcessor() {
            var self = this;
            this.require = require;
            this.codeHighlighter = require("lib/ace/ext/static_highlight");
            this.selectedCodeTheme = new ko.observable("solarized_dark");
            this.themeOptions = [];
            this.currentTheme = new ko.observable();
            this.dom = require("lib/ace/lib/dom");
            this.deferred = undefined;
            var aceCoffeeMode = (require("lib/ace/mode/coffee")).Mode;
            this.coffeeMode = new aceCoffeeMode();
            var aceJavscriptMode = (require("lib/ace/mode/javascript")).Mode;
            this.javascriptMode = new aceJavscriptMode();
            this.properties = [];

            this.setCurrentTheme = function () {
                console.log('setting current theme to : ' + "lib/ace/theme/" + self.selectedCodeTheme());
                var theme = self.require("lib/ace/theme/" + self.selectedCodeTheme());
                if (theme)
                    self.currentTheme(theme);

            };
            self.setCurrentTheme();

//            ko.computed(function () {
//                if (self.selectedCodeTheme()) {
//                    console.log(self.selectedCodeTheme());
//                    self.setCurrentTheme();
//                }
//            }).extend({
//                    throttle: 1000
//                });
        }

        CodeProcessor.prototype.buildPropertyList = function (context, proto, done) {
            var jsStr = '', coffeeStr = '', prop, property;
            var _this = this;
            Object.keys(context).forEach(function (prop) {
                if (context[prop] instanceof Function) {
                    jsStr = context[prop].toString();
                    try {
                        coffeeStr = Js2coffee.build(jsStr);
                        property = { name: (proto ? 'prototype.' : '') + prop + '()', jsStr: _this.highlight(jsStr, _this.javascriptMode), coffeeStr: _this.highlight(coffeeStr, _this.coffeeMode)};
                        _this.properties.push(property);
                    } catch (err) {
                        property = { name: (proto ? 'prototype.' : '') + prop + '()', jsStr: _this.highlight(jsStr, _this.javascriptMode), coffeeStr: ''};
                        _this.properties.push(property);
                    }

                } else {
                    var objSrc = ToSource(context[prop]);
                    objSrc = prop + ' = ' + objSrc
                    property = {  name: (proto ? 'prototype.' : '') + prop, jsStr: _this.highlight(objSrc.replace(prop + ' = ',''), _this.javascriptMode), coffeeStr: _this.highlight(Js2coffee.build(objSrc).replace(prop + ' = ','').replace(prop + ' =\n',''), _this.coffeeMode)};
                    _this.properties.push(property);
                }

            });

            if (!proto && Object.keys(context.__proto__).length > 0) {
                this.buildPropertyList(context.__proto__, true, done);
            }
            else {
                done(_this.properties);
            }

        };

        CodeProcessor.prototype.highlight = function (code, mode) {
            var highlighted = this.codeHighlighter.render(code, mode, this.currentTheme());

            this.dom.importCssString(highlighted.css, "ace_highlight");

            return highlighted.html;
        };


        CodeProcessor.prototype.process = function (codeModel) {
            this.deferred = when.defer();
            var _this = this;

            this.properties = [];
            this.buildPropertyList(codeModel.jsContext, false, function (properties) {

                codeModel.properties(properties);

                _this.deferred.resolve(codeModel);
                $.get('_src/' + codeModel.moduleName + '.js',function (jsStr) {
                    jsStr = jsStr.replace('\/\/ Generated by CoffeeScript 1.6.3\n', '');
                    codeModel.jsSourceStr(jsStr.trim());
                    _this.deferred.resolve(codeModel);

                }).fail(function () {
                        codeModel.jsSourceStr(ToSource(codeModel.jsFunctionOrObject));
                        _this.deferred.resolve(codeModel);
                    });


            });


            return this.deferred.promise;
        };

        return CodeProcessor;
    });